build:
    image: ubuntu:latest
    variables:
        DEBIAN_FRONTEND: noninteractive
        PIPX_BIN_DIR: /usr/local/bin
    before_script:
        - apt-get update
        - apt-get install python pipx device-tree-compiler cmake ninja-build
        - pipx install west
    script:
        - west build -b capbot
mypy:
    image: python:latest
    stage: test
    before_script:
        - python -m pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install mypy
    script:
        - mypy $(git ls-files '*.py')

pylint:
    image: python:latest
    stage: test
    before_script:
        - python -m pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install pylint
    script:
        - pylint $(git ls-files '*.py')
    allow_failure: true
