build:
    stage: build
    image: ghcr.io/nrfconnect/sdk-nrf-toolchain:v2.7.0
    variables:
        DEBIAN_FRONTEND: noninteractive # CI is a non-interactive shell
        ACCEPT_JLINK_LICENSE: 0         # JLink isn't needed for building
    script:
        - cd robot
        - west init --local --manifest-file west-ncs2.7.0.yml
        - west update
        - west build --board capbot
    cache:
        key: west-cache
        paths:
        - deps/
    artifacts:
      when: on_success
      expire_in: "1 week"
      paths:
        - robot/build/

mypy:
    image: python:latest
    stage: test
    before_script:
        - python -m pip install --upgrade pip
        - pip install '.'
        - pip install mypy
    script:
        - mypy $(git ls-files '*.py')

ruff:
    image: python:latest
    stage: test
    before_script:
        - python -m pip install --upgrade pip
        - pip install '.'
        - pip install ruff
    script:
        - ruff check $(git ls-files '*.py')
    allow_failure: true
